apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: %PLACEHOLDER%
  name: all-access
rules:
  - apiGroups: ['']
    resources:
      [
        'pods',
        'services',
        'deployments',
        'replicasets',
        'replicationcontrollers',
        'configmaps',
        'secrets',
        'daemonsets',
        'statefulsets',
        'pods/exec',
        'pods/log',
        'pods/portforward',
        'horizontalpodautoscalers',
      ]
    verbs: ['*']
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets', 'daemonsets', 'statefulsets']
    verbs: ['*']
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['*']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roles', 'rolebindings']
    verbs: ['*']
  - apiGroups: ['batch']
    resources: ['jobs', 'cronjobs']
    verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: all-access-binding
  namespace: %PLACEHOLDER%
subjects:
  - kind: User
    name: %PLACEHOLDER%
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: all-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mgmt-app-quota
  namespace: %PLACEHOLDER%
spec:
  hard:
    pods: '7'
    services: '5'
    requests.cpu: '4'
    requests.memory: 4Gi
    limits.cpu: '4'
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mgmt-app-limitrange
  namespace: %PLACEHOLDER%
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 512Mi
        cpu: 500m
      type: Container
